#!/bin/sh
# File generated by ocamlbuild

cd '/Users/yuezhuang/Documents/projects/mem copy/celia-malloc/mman'

rm -f mman_asyn.cmi
rm -f mman_asyn.cmo
rm -f mman_dabs.cmi
rm -f mman_dabs.cmo
rm -f mman_dflap.cmi
rm -f mman_dflap.cmo
rm -f mman_emls.cmi
rm -f mman_emls.cmo
rm -f mman_env.cmi
rm -f mman_env.cmo
rm -f mman_options.cmi
rm -f mman_options.cmo
rm -f mman_sha.cmi
rm -f mman_sha.cmo
rm -f mman_svar.cmi
rm -f mman_svar.cmo
rm -f mman_valap.cmi
rm -f mman_valap.cmo
# Also clean the script itself
rm -f '/Users/yuezhuang/Documents/projects/mem copy/celia-malloc/mman/_build/sanitize.sh'
